version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:  
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: